server:
  port: 9003
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application.name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  flyway:
    url: ${FLYWAY_DB_URL:jdbc:postgresql://localhost:5432/storedb_order}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  r2dbc:
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/storedb_order}
    pool:
      initial-size: 5
      max-create-connection-time: 2s
      max-size: 10

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, refresh